import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";

test("security headers, auth, atomic concurrent writes and image validation", async (t) => {
  const directory = await mkdtemp(join(tmpdir(), "vi-security-"));
  process.env.DATA_FILE = join(directory, "store.json");
  const { default: app } = await import("../src/app.js");
  const server = app.listen(0, "127.0.0.1");
  await new Promise((done) => server.once("listening", done));
  t.after(async () => { await new Promise((done) => server.close(done)); await rm(directory, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const send = (path, body, extra = {}) => fetch(base + path, { method: "POST", headers: { "Content-Type": "application/json", ...extra }, body: JSON.stringify(body) });
  const health = await fetch(base + "/health");
  assert.equal(health.headers.get("x-content-type-options"), "nosniff");
  assert.equal(health.headers.get("x-frame-options"), "SAMEORIGIN");
  assert.equal((await fetch(base + "/admin/products")).status, 401);
  assert.equal((await send("/auth/setup", {}, { Origin: "https://untrusted.example" })).status, 403);
  const credentials = { email: "admin@example.com", password: "security-test-password" };
  assert.equal((await send("/auth/setup", credentials)).status, 201);
  const login = await send("/auth/login", credentials);
  assert.equal(login.status, 200);
  assert.match(login.headers.get("set-cookie"), /HttpOnly/);
  const cookie = login.headers.get("set-cookie").split(";")[0];
  const results = await Promise.all(Array.from({ length: 12 }, (_, index) => send("/admin/categories", { name: `Test ${index}` }, { Cookie: cookie })));
  assert.ok(results.every((response) => response.status === 201));
  assert.equal(JSON.parse(await readFile(process.env.DATA_FILE)).categories.length, 12);
  assert.equal((await send("/admin/categories", { name: "Unsafe", imageUrl: "javascript:alert(1)" }, { Cookie: cookie })).status, 400);
  const fake = new FormData();
  fake.append("image", new Blob(["not an image"], { type: "image/png" }), "fake.png");
  assert.equal((await fetch(base + "/admin/upload", { method: "POST", headers: { Cookie: cookie }, body: fake })).status, 400);
  const actual = new FormData();
  actual.append("image", new Blob([await sharp({ create: { width: 10, height: 10, channels: 3, background: "white" } }).png().toBuffer()], { type: "image/png" }), "real.png");
  const uploaded = await fetch(base + "/admin/upload", { method: "POST", headers: { Cookie: cookie }, body: actual });
  assert.equal(uploaded.status, 201);
  const { url } = await uploaded.json();
  assert.match(url, /\.webp$/);
  // Only remove the unique synthetic fixture generated by this test.
  await rm(join("server", url), { force: true });
  const originalNow = Date.now;
  try { Date.now = () => originalNow() + 25 * 60 * 60 * 1000; assert.equal((await fetch(base + "/admin/categories", { headers: { Cookie: cookie } })).status, 401); }
  finally { Date.now = originalNow; }
  for (let attempt = 0; attempt < 10; attempt++) await send("/auth/login", { ...credentials, password: "wrong" });
  assert.equal((await send("/auth/login", credentials)).status, 429);
});
